services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - server-client-network
      - server-logger-network
    ports:
      - "4502:4502"
    environment:
      - SERVER_PORT=4502
      - LOGGER_SERVER_PORT=7001
      - LOGGER_SERVER_NAME=logger
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - server-client-network
    depends_on:
      server:
        condition: service_started
      logger:
        condition: service_started
    environment:
      - SERVER_PORT=4502
      - SERVER_HOST=server
    deploy:
      replicas: 100
  logger:
    build:
      context: logger
      dockerfile: Dockerfile
    networks:
      - server-logger-network
    ports:
      - "7001:7001"
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./data/data.txt:/tcp/data/data.txt
  clientlogger:
    build:
      context: logger/clientsLogger
      dockerfile: Dockerfile
    ports:
      - "7502:7502"
    networks:
      - server-logger-network
      - server-client-logger-network
    volumes:
      - ./data/infoForClients.txt:/tcp/infoForClients.txt
    depends_on:
      server:
        condition: service_started
networks:
  server-client-network:
    driver: bridge
  server-logger-network:
    driver: bridge
  server-client-logger-network:
    driver: bridge